# Generated by Django 5.2 on 2025-05-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=40)),
                ('join_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
